services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.5
    command: start
    restart: unless-stopped
    depends_on:
      - keycloakdb
    env_file: .env
  
  keycloakdb:
    image: postgres:17.2-alpine
    restart: unless-stopped
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    env_file: .env

volumes:
  keycloak-data:
    driver: local
